#include "lua_native_binding.hpp"
#include "natives.hpp"

namespace lua::native
{
	static bool LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_MENU()
	{
		auto retval = (bool)LOBBY::LOBBY_AUTO_MULTIPLAYER_MENU();
		return retval;
	}

	static bool LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_FREEMODE()
	{
		auto retval = (bool)LOBBY::LOBBY_AUTO_MULTIPLAYER_FREEMODE();
		return retval;
	}

	static void LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MULTIPLAYER(bool toggle)
	{
		LOBBY::LOBBY_SET_AUTO_MULTIPLAYER(toggle);
	}

	static bool LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_EVENT()
	{
		auto retval = (bool)LOBBY::LOBBY_AUTO_MULTIPLAYER_EVENT();
		return retval;
	}

	static void LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MULTIPLAYER_EVENT(bool toggle)
	{
		LOBBY::LOBBY_SET_AUTO_MULTIPLAYER_EVENT(toggle);
	}

	static bool LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_RANDOM_JOB()
	{
		auto retval = (bool)LOBBY::LOBBY_AUTO_MULTIPLAYER_RANDOM_JOB();
		return retval;
	}

	static void LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MP_RANDOM_JOB(bool toggle)
	{
		LOBBY::LOBBY_SET_AUTO_MP_RANDOM_JOB(toggle);
	}

	static void LUA_NATIVE_LOBBY_SHUTDOWN_SESSION_CLEARS_AUTO_MULTIPLAYER(bool toggle)
	{
		LOBBY::SHUTDOWN_SESSION_CLEARS_AUTO_MULTIPLAYER(toggle);
	}

	void init_native_binding_LOBBY(sol::state& L)
	{
		auto LOBBY = L["LOBBY"].get_or_create<sol::table>();
		LOBBY.set_function("LOBBY_AUTO_MULTIPLAYER_MENU", LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_MENU);
		LOBBY.set_function("LOBBY_AUTO_MULTIPLAYER_FREEMODE", LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_FREEMODE);
		LOBBY.set_function("LOBBY_SET_AUTO_MULTIPLAYER", LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MULTIPLAYER);
		LOBBY.set_function("LOBBY_AUTO_MULTIPLAYER_EVENT", LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_EVENT);
		LOBBY.set_function("LOBBY_SET_AUTO_MULTIPLAYER_EVENT", LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MULTIPLAYER_EVENT);
		LOBBY.set_function("LOBBY_AUTO_MULTIPLAYER_RANDOM_JOB", LUA_NATIVE_LOBBY_LOBBY_AUTO_MULTIPLAYER_RANDOM_JOB);
		LOBBY.set_function("LOBBY_SET_AUTO_MP_RANDOM_JOB", LUA_NATIVE_LOBBY_LOBBY_SET_AUTO_MP_RANDOM_JOB);
		LOBBY.set_function("SHUTDOWN_SESSION_CLEARS_AUTO_MULTIPLAYER", LUA_NATIVE_LOBBY_SHUTDOWN_SESSION_CLEARS_AUTO_MULTIPLAYER);
	}
}
